---
title: "Simulation_S"
author: "Kalle Leppälä"
date: "2023-02-22"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
set.seed(1)
library(ggplot2)
source("tools.R")
```

## SIMULATING THE 32 ADMIXTURE SCENARIOS WE ARE ABLE TO DETECT IN TREE S

```{r simulation}
tables <- list()
lambda <- 1
N <- 1000000

# P1 -> P3
LL <- list(lambda = lambda, inhabitants = character(0), samples = list(P1 = 0), switches = list(LR = c(1, 1)))
LR <- list(lambda = lambda, inhabitants = character(0), samples = list(P2 = 0), switches = list(RR = c(2, 1)))
RL <- list(lambda = lambda, inhabitants = character(0), samples = list(P3 = 0), switches = list(RR = c(1, 1), LL = c(0.5, 0.1)))
RR <- list(lambda = lambda, inhabitants = character(0), samples = list(P4 = 0), switches = list(OG = c(3, 1)))
OG <- list(lambda = lambda, inhabitants = character(0), samples = list(P5 = 0), switches = list())
graph <- list(LL = LL, LR = LR, RL = RL, RR = RR, OG = OG)
abbababa <- character(0)
for (k in seq(1, N)) {
	abbababa[length(abbababa) + 1] <- pattern(solve_tree(graph))
}
table <- table(abbababa)
tables[[length(tables) + 1]] <- table
# P3 -> P1
LL <- list(lambda = lambda, inhabitants = character(0), samples = list(P1 = 0), switches = list(LR = c(1, 1), RL = c(0.5, 0.1)))
LR <- list(lambda = lambda, inhabitants = character(0), samples = list(P2 = 0), switches = list(RR = c(2, 1)))
RL <- list(lambda = lambda, inhabitants = character(0), samples = list(P3 = 0), switches = list(RR = c(1, 1)))
RR <- list(lambda = lambda, inhabitants = character(0), samples = list(P4 = 0), switches = list(OG = c(3, 1)))
OG <- list(lambda = lambda, inhabitants = character(0), samples = list(P5 = 0), switches = list())
graph <- list(LL = LL, LR = LR, RL = RL, RR = RR, OG = OG)
abbababa <- character(0)
for (k in seq(1, N)) {
	abbababa[length(abbababa) + 1] <- pattern(solve_tree(graph))
}
table <- table(abbababa)
tables[[length(tables) + 1]] <- table
# P1 -> P4
LL <- list(lambda = lambda, inhabitants = character(0), samples = list(P1 = 0), switches = list(LR = c(1, 1)))
LR <- list(lambda = lambda, inhabitants = character(0), samples = list(P2 = 0), switches = list(RR = c(2, 1)))
RL <- list(lambda = lambda, inhabitants = character(0), samples = list(P3 = 0), switches = list(RR = c(1, 1)))
RR <- list(lambda = lambda, inhabitants = character(0), samples = list(P4 = 0), switches = list(OG = c(3, 1), LL = c(0.5, 0.1)))
OG <- list(lambda = lambda, inhabitants = character(0), samples = list(P5 = 0), switches = list())
graph <- list(LL = LL, LR = LR, RL = RL, RR = RR, OG = OG)
abbababa <- character(0)
for (k in seq(1, N)) {
	abbababa[length(abbababa) + 1] <- pattern(solve_tree(graph))
}
table <- table(abbababa)
tables[[length(tables) + 1]] <- table
# P4 -> P1
LL <- list(lambda = lambda, inhabitants = character(0), samples = list(P1 = 0), switches = list(LR = c(1, 1), RR = c(0.5, 0.1)))
LR <- list(lambda = lambda, inhabitants = character(0), samples = list(P2 = 0), switches = list(RR = c(2, 1)))
RL <- list(lambda = lambda, inhabitants = character(0), samples = list(P3 = 0), switches = list(RR = c(1, 1)))
RR <- list(lambda = lambda, inhabitants = character(0), samples = list(P4 = 0), switches = list(OG = c(3, 1)))
OG <- list(lambda = lambda, inhabitants = character(0), samples = list(P5 = 0), switches = list())
graph <- list(LL = LL, LR = LR, RL = RL, RR = RR, OG = OG)
abbababa <- character(0)
for (k in seq(1, N)) {
	abbababa[length(abbababa) + 1] <- pattern(solve_tree(graph))
}
table <- table(abbababa)
tables[[length(tables) + 1]] <- table
# P2 -> P3
LL <- list(lambda = lambda, inhabitants = character(0), samples = list(P1 = 0), switches = list(LR = c(1, 1)))
LR <- list(lambda = lambda, inhabitants = character(0), samples = list(P2 = 0), switches = list(RR = c(2, 1)))
RL <- list(lambda = lambda, inhabitants = character(0), samples = list(P3 = 0), switches = list(RR = c(1, 1), LR = c(0.5, 0.1)))
RR <- list(lambda = lambda, inhabitants = character(0), samples = list(P4 = 0), switches = list(OG = c(3, 1)))
OG <- list(lambda = lambda, inhabitants = character(0), samples = list(P5 = 0), switches = list())
graph <- list(LL = LL, LR = LR, RL = RL, RR = RR, OG = OG)
abbababa <- character(0)
for (k in seq(1, N)) {
	abbababa[length(abbababa) + 1] <- pattern(solve_tree(graph))
}
table <- table(abbababa)
tables[[length(tables) + 1]] <- table
# P3 -> P2
LL <- list(lambda = lambda, inhabitants = character(0), samples = list(P1 = 0), switches = list(LR = c(1, 1)))
LR <- list(lambda = lambda, inhabitants = character(0), samples = list(P2 = 0), switches = list(RR = c(2, 1), RL = c(0.5, 0.1)))
RL <- list(lambda = lambda, inhabitants = character(0), samples = list(P3 = 0), switches = list(RR = c(1, 1)))
RR <- list(lambda = lambda, inhabitants = character(0), samples = list(P4 = 0), switches = list(OG = c(3, 1)))
OG <- list(lambda = lambda, inhabitants = character(0), samples = list(P5 = 0), switches = list())
graph <- list(LL = LL, LR = LR, RL = RL, RR = RR, OG = OG)
abbababa <- character(0)
for (k in seq(1, N)) {
	abbababa[length(abbababa) + 1] <- pattern(solve_tree(graph))
}
table <- table(abbababa)
tables[[length(tables) + 1]] <- table
# P2 -> P4
LL <- list(lambda = lambda, inhabitants = character(0), samples = list(P1 = 0), switches = list(LR = c(1, 1)))
LR <- list(lambda = lambda, inhabitants = character(0), samples = list(P2 = 0), switches = list(RR = c(2, 1)))
RL <- list(lambda = lambda, inhabitants = character(0), samples = list(P3 = 0), switches = list(RR = c(1, 1)))
RR <- list(lambda = lambda, inhabitants = character(0), samples = list(P4 = 0), switches = list(OG = c(3, 1), LR = c(0.5, 0.1)))
OG <- list(lambda = lambda, inhabitants = character(0), samples = list(P5 = 0), switches = list())
graph <- list(LL = LL, LR = LR, RL = RL, RR = RR, OG = OG)
abbababa <- character(0)
for (k in seq(1, N)) {
	abbababa[length(abbababa) + 1] <- pattern(solve_tree(graph))
}
table <- table(abbababa)
tables[[length(tables) + 1]] <- table
# P4 -> P2
LL <- list(lambda = lambda, inhabitants = character(0), samples = list(P1 = 0), switches = list(LR = c(1, 1)))
LR <- list(lambda = lambda, inhabitants = character(0), samples = list(P2 = 0), switches = list(RL = c(2, 1), RR = c(0.5, 0.1)))
RL <- list(lambda = lambda, inhabitants = character(0), samples = list(P3 = 0), switches = list(OG = c(3, 1)))
RR <- list(lambda = lambda, inhabitants = character(0), samples = list(P4 = 0), switches = list(RL = c(1, 1)))
OG <- list(lambda = lambda, inhabitants = character(0), samples = list(P5 = 0), switches = list())
graph <- list(LL = LL, LR = LR, RL = RL, RR = RR, OG = OG)
abbababa <- character(0)
for (k in seq(1, N)) {
	abbababa[length(abbababa) + 1] <- pattern(solve_tree(graph))
}
table <- table(abbababa)
tables[[length(tables) + 1]] <- table
# P12 -> P3
LL <- list(lambda = lambda, inhabitants = character(0), samples = list(P1 = 0), switches = list(LR = c(0.75, 1)))
LR <- list(lambda = lambda, inhabitants = character(0), samples = list(P2 = 0), switches = list(RR = c(2.25, 1)))
RL <- list(lambda = lambda, inhabitants = character(0), samples = list(P3 = 0), switches = list(RR = c(1.5, 1), LR = c(1.125, 0.1)))
RR <- list(lambda = lambda, inhabitants = character(0), samples = list(P4 = 0), switches = list(OG = c(3, 1)))
OG <- list(lambda = lambda, inhabitants = character(0), samples = list(P5 = 0), switches = list())
graph <- list(LL = LL, LR = LR, RL = RL, RR = RR, OG = OG)
abbababa <- character(0)
for (k in seq(1, N)) {
	abbababa[length(abbababa) + 1] <- pattern(solve_tree(graph))
}
table <- table(abbababa)
tables[[length(tables) + 1]] <- table
# P3 -> P12
LL <- list(lambda = lambda, inhabitants = character(0), samples = list(P1 = 0), switches = list(LR = c(0.75, 1)))
LR <- list(lambda = lambda, inhabitants = character(0), samples = list(P2 = 0), switches = list(RR = c(2.25, 1), RL = c(1.125, 0.1)))
RL <- list(lambda = lambda, inhabitants = character(0), samples = list(P3 = 0), switches = list(RR = c(1.5, 1)))
RR <- list(lambda = lambda, inhabitants = character(0), samples = list(P4 = 0), switches = list(OG = c(3, 1)))
OG <- list(lambda = lambda, inhabitants = character(0), samples = list(P5 = 0), switches = list())
graph <- list(LL = LL, LR = LR, RL = RL, RR = RR, OG = OG)
abbababa <- character(0)
for (k in seq(1, N)) {
	abbababa[length(abbababa) + 1] <- pattern(solve_tree(graph))
}
table <- table(abbababa)
tables[[length(tables) + 1]] <- table
# P12 -> P4
LL <- list(lambda = lambda, inhabitants = character(0), samples = list(P1 = 0), switches = list(LR = c(0.75, 1)))
LR <- list(lambda = lambda, inhabitants = character(0), samples = list(P2 = 0), switches = list(RR = c(2.25, 1)))
RL <- list(lambda = lambda, inhabitants = character(0), samples = list(P3 = 0), switches = list(RR = c(1.5, 1)))
RR <- list(lambda = lambda, inhabitants = character(0), samples = list(P4 = 0), switches = list(OG = c(3, 1), LR = c(1.125, 0.1)))
OG <- list(lambda = lambda, inhabitants = character(0), samples = list(P5 = 0), switches = list())
graph <- list(LL = LL, LR = LR, RL = RL, RR = RR, OG = OG)
abbababa <- character(0)
for (k in seq(1, N)) {
	abbababa[length(abbababa) + 1] <- pattern(solve_tree(graph))
}
table <- table(abbababa)
tables[[length(tables) + 1]] <- table
# P4 -> P12
LL <- list(lambda = lambda, inhabitants = character(0), samples = list(P1 = 0), switches = list(LR = c(0.75, 1)))
LR <- list(lambda = lambda, inhabitants = character(0), samples = list(P2 = 0), switches = list(RL = c(2.25, 1), RR = c(1.125, 0.1)))
RL <- list(lambda = lambda, inhabitants = character(0), samples = list(P3 = 0), switches = list(OG = c(3, 1)))
RR <- list(lambda = lambda, inhabitants = character(0), samples = list(P4 = 0), switches = list(RL = c(1.5, 1)))
OG <- list(lambda = lambda, inhabitants = character(0), samples = list(P5 = 0), switches = list())
graph <- list(LL = LL, LR = LR, RL = RL, RR = RR, OG = OG)
abbababa <- character(0)
for (k in seq(1, N)) {
	abbababa[length(abbababa) + 1] <- pattern(solve_tree(graph))
}
table <- table(abbababa)
tables[[length(tables) + 1]] <- table
# P34 -> P1
LL <- list(lambda = lambda, inhabitants = character(0), samples = list(P1 = 0), switches = list(LR = c(1.5, 1), RR = c(1.125, 0.1)))
LR <- list(lambda = lambda, inhabitants = character(0), samples = list(P2 = 0), switches = list(RR = c(2.25, 1)))
RL <- list(lambda = lambda, inhabitants = character(0), samples = list(P3 = 0), switches = list(RR = c(0.75, 1)))
RR <- list(lambda = lambda, inhabitants = character(0), samples = list(P4 = 0), switches = list(OG = c(3, 1)))
OG <- list(lambda = lambda, inhabitants = character(0), samples = list(P5 = 0), switches = list())
graph <- list(LL = LL, LR = LR, RL = RL, RR = RR, OG = OG)
abbababa <- character(0)
for (k in seq(1, N)) {
	abbababa[length(abbababa) + 1] <- pattern(solve_tree(graph))
}
table <- table(abbababa)
tables[[length(tables) + 1]] <- table
# P1 -> P34
LL <- list(lambda = lambda, inhabitants = character(0), samples = list(P1 = 0), switches = list(LR = c(1.5, 1)))
LR <- list(lambda = lambda, inhabitants = character(0), samples = list(P2 = 0), switches = list(RR = c(2.25, 1)))
RL <- list(lambda = lambda, inhabitants = character(0), samples = list(P3 = 0), switches = list(RR = c(0.75, 1)))
RR <- list(lambda = lambda, inhabitants = character(0), samples = list(P4 = 0), switches = list(OG = c(3, 1), LL = c(1.125, 0.1)))
OG <- list(lambda = lambda, inhabitants = character(0), samples = list(P5 = 0), switches = list())
graph <- list(LL = LL, LR = LR, RL = RL, RR = RR, OG = OG)
abbababa <- character(0)
for (k in seq(1, N)) {
	abbababa[length(abbababa) + 1] <- pattern(solve_tree(graph))
}
table <- table(abbababa)
tables[[length(tables) + 1]] <- table
# P34 -> P2
LL <- list(lambda = lambda, inhabitants = character(0), samples = list(P1 = 0), switches = list(RR = c(2.25, 1)))
LR <- list(lambda = lambda, inhabitants = character(0), samples = list(P2 = 0), switches = list(LL = c(1.5, 1), RR = c(1.125, 0.1)))
RL <- list(lambda = lambda, inhabitants = character(0), samples = list(P3 = 0), switches = list(RR = c(0.75, 1)))
RR <- list(lambda = lambda, inhabitants = character(0), samples = list(P4 = 0), switches = list(OG = c(3, 1)))
OG <- list(lambda = lambda, inhabitants = character(0), samples = list(P5 = 0), switches = list())
graph <- list(LL = LL, LR = LR, RL = RL, RR = RR, OG = OG)
abbababa <- character(0)
for (k in seq(1, N)) {
	abbababa[length(abbababa) + 1] <- pattern(solve_tree(graph))
}
table <- table(abbababa)
tables[[length(tables) + 1]] <- table
# P2 -> P34
LL <- list(lambda = lambda, inhabitants = character(0), samples = list(P1 = 0), switches = list(LR = c(1.5, 1)))
LR <- list(lambda = lambda, inhabitants = character(0), samples = list(P2 = 0), switches = list(RR = c(2.25, 1)))
RL <- list(lambda = lambda, inhabitants = character(0), samples = list(P3 = 0), switches = list(RR = c(0.75, 1)))
RR <- list(lambda = lambda, inhabitants = character(0), samples = list(P4 = 0), switches = list(OG = c(3, 1), LR = c(1.125, 0.1)))
OG <- list(lambda = lambda, inhabitants = character(0), samples = list(P5 = 0), switches = list())
graph <- list(LL = LL, LR = LR, RL = RL, RR = RR, OG = OG)
abbababa <- character(0)
for (k in seq(1, N)) {
	abbababa[length(abbababa) + 1] <- pattern(solve_tree(graph))
}
table <- table(abbababa)
tables[[length(tables) + 1]] <- table
# P1 -> P5
LL <- list(lambda = lambda, inhabitants = character(0), samples = list(P1 = 0), switches = list(LR = c(1, 1)))
LR <- list(lambda = lambda, inhabitants = character(0), samples = list(P2 = 0), switches = list(RR = c(2, 1)))
RL <- list(lambda = lambda, inhabitants = character(0), samples = list(P3 = 0), switches = list(RR = c(1, 1)))
RR <- list(lambda = lambda, inhabitants = character(0), samples = list(P4 = 0), switches = list(OG = c(3, 1)))
OG <- list(lambda = lambda, inhabitants = character(0), samples = list(P5 = 0), switches = list(LL = c(0.5, 0.1)))
graph <- list(LL = LL, LR = LR, RL = RL, RR = RR, OG = OG)
abbababa <- character(0)
for (k in seq(1, N)) {
	abbababa[length(abbababa) + 1] <- pattern(solve_tree(graph))
}
table <- table(abbababa)
tables[[length(tables) + 1]] <- table
# P5 -> P1
LL <- list(lambda = lambda, inhabitants = character(0), samples = list(P1 = 0), switches = list(LR = c(1, 1), OG = c(0.5, 0.1)))
LR <- list(lambda = lambda, inhabitants = character(0), samples = list(P2 = 0), switches = list(RR = c(2, 1)))
RL <- list(lambda = lambda, inhabitants = character(0), samples = list(P3 = 0), switches = list(RR = c(1, 1)))
RR <- list(lambda = lambda, inhabitants = character(0), samples = list(P4 = 0), switches = list(OG = c(3, 1)))
OG <- list(lambda = lambda, inhabitants = character(0), samples = list(P5 = 0), switches = list())
graph <- list(LL = LL, LR = LR, RL = RL, RR = RR, OG = OG)
abbababa <- character(0)
for (k in seq(1, N)) {
	abbababa[length(abbababa) + 1] <- pattern(solve_tree(graph))
}
table <- table(abbababa)
tables[[length(tables) + 1]] <- table
# P2 -> P5
LL <- list(lambda = lambda, inhabitants = character(0), samples = list(P1 = 0), switches = list(LR = c(1, 1)))
LR <- list(lambda = lambda, inhabitants = character(0), samples = list(P2 = 0), switches = list(RR = c(2, 1)))
RL <- list(lambda = lambda, inhabitants = character(0), samples = list(P3 = 0), switches = list(RR = c(1, 1)))
RR <- list(lambda = lambda, inhabitants = character(0), samples = list(P4 = 0), switches = list(OG = c(3, 1)))
OG <- list(lambda = lambda, inhabitants = character(0), samples = list(P5 = 0), switches = list(LR = c(0.5, 0.1)))
graph <- list(LL = LL, LR = LR, RL = RL, RR = RR, OG = OG)
abbababa <- character(0)
for (k in seq(1, N)) {
	abbababa[length(abbababa) + 1] <- pattern(solve_tree(graph))
}
table <- table(abbababa)
tables[[length(tables) + 1]] <- table
# P5 -> P2
LL <- list(lambda = lambda, inhabitants = character(0), samples = list(P1 = 0), switches = list(LR = c(1, 1)))
LR <- list(lambda = lambda, inhabitants = character(0), samples = list(P2 = 0), switches = list(RR = c(2, 1), OG = c(0.5, 0.1)))
RL <- list(lambda = lambda, inhabitants = character(0), samples = list(P3 = 0), switches = list(RR = c(1, 1)))
RR <- list(lambda = lambda, inhabitants = character(0), samples = list(P4 = 0), switches = list(OG = c(3, 1)))
OG <- list(lambda = lambda, inhabitants = character(0), samples = list(P5 = 0), switches = list())
graph <- list(LL = LL, LR = LR, RL = RL, RR = RR, OG = OG)
abbababa <- character(0)
for (k in seq(1, N)) {
	abbababa[length(abbababa) + 1] <- pattern(solve_tree(graph))
}
table <- table(abbababa)
tables[[length(tables) + 1]] <- table
# P3 -> P5
LL <- list(lambda = lambda, inhabitants = character(0), samples = list(P1 = 0), switches = list(LR = c(1, 1)))
LR <- list(lambda = lambda, inhabitants = character(0), samples = list(P2 = 0), switches = list(RR = c(2, 1)))
RL <- list(lambda = lambda, inhabitants = character(0), samples = list(P3 = 0), switches = list(RR = c(1, 1)))
RR <- list(lambda = lambda, inhabitants = character(0), samples = list(P4 = 0), switches = list(OG = c(3, 1)))
OG <- list(lambda = lambda, inhabitants = character(0), samples = list(P5 = 0), switches = list(RL = c(0.5, 0.1)))
graph <- list(LL = LL, LR = LR, RL = RL, RR = RR, OG = OG)
abbababa <- character(0)
for (k in seq(1, N)) {
	abbababa[length(abbababa) + 1] <- pattern(solve_tree(graph))
}
table <- table(abbababa)
tables[[length(tables) + 1]] <- table
# P5 -> P3
LL <- list(lambda = lambda, inhabitants = character(0), samples = list(P1 = 0), switches = list(LR = c(1, 1)))
LR <- list(lambda = lambda, inhabitants = character(0), samples = list(P2 = 0), switches = list(RR = c(2, 1)))
RL <- list(lambda = lambda, inhabitants = character(0), samples = list(P3 = 0), switches = list(RR = c(1, 1), OG = c(0.5, 0.1)))
RR <- list(lambda = lambda, inhabitants = character(0), samples = list(P4 = 0), switches = list(OG = c(3, 1)))
OG <- list(lambda = lambda, inhabitants = character(0), samples = list(P5 = 0), switches = list())
graph <- list(LL = LL, LR = LR, RL = RL, RR = RR, OG = OG)
abbababa <- character(0)
for (k in seq(1, N)) {
	abbababa[length(abbababa) + 1] <- pattern(solve_tree(graph))
}
table <- table(abbababa)
tables[[length(tables) + 1]] <- table
# P4 -> P5
LL <- list(lambda = lambda, inhabitants = character(0), samples = list(P1 = 0), switches = list(LR = c(1, 1)))
LR <- list(lambda = lambda, inhabitants = character(0), samples = list(P2 = 0), switches = list(RR = c(2, 1)))
RL <- list(lambda = lambda, inhabitants = character(0), samples = list(P3 = 0), switches = list(RR = c(1, 1)))
RR <- list(lambda = lambda, inhabitants = character(0), samples = list(P4 = 0), switches = list(OG = c(3, 1)))
OG <- list(lambda = lambda, inhabitants = character(0), samples = list(P5 = 0), switches = list(RR = c(0.5, 0.1)))
graph <- list(LL = LL, LR = LR, RL = RL, RR = RR, OG = OG)
abbababa <- character(0)
for (k in seq(1, N)) {
	abbababa[length(abbababa) + 1] <- pattern(solve_tree(graph))
}
table <- table(abbababa)
tables[[length(tables) + 1]] <- table
# P5 -> P4
LL <- list(lambda = lambda, inhabitants = character(0), samples = list(P1 = 0), switches = list(LR = c(1, 1)))
LR <- list(lambda = lambda, inhabitants = character(0), samples = list(P2 = 0), switches = list(RL = c(2, 1)))
RL <- list(lambda = lambda, inhabitants = character(0), samples = list(P3 = 0), switches = list(OG = c(3, 1)))
RR <- list(lambda = lambda, inhabitants = character(0), samples = list(P4 = 0), switches = list(RL = c(1, 1), OG = c(0.5, 0.1)))
OG <- list(lambda = lambda, inhabitants = character(0), samples = list(P5 = 0), switches = list())
graph <- list(LL = LL, LR = LR, RL = RL, RR = RR, OG = OG)
abbababa <- character(0)
for (k in seq(1, N)) {
	abbababa[length(abbababa) + 1] <- pattern(solve_tree(graph))
}
table <- table(abbababa)
tables[[length(tables) + 1]] <- table
# P12345 -> P1
LL <- list(lambda = lambda, inhabitants = character(0), samples = list(P1 = 0), switches = list(LR = c(1, 1), GH = c(0.5, 0.1)))
LR <- list(lambda = lambda, inhabitants = character(0), samples = list(P2 = 0), switches = list(RR = c(2, 1)))
RL <- list(lambda = lambda, inhabitants = character(0), samples = list(P3 = 0), switches = list(RR = c(1, 1)))
RR <- list(lambda = lambda, inhabitants = character(0), samples = list(P4 = 0), switches = list(OG = c(3, 1)))
OG <- list(lambda = lambda, inhabitants = character(0), samples = list(P5 = 0), switches = list())
GH <- list(lambda = lambda, inhabitants = character(0), samples = list(), switches = list(OG = c(3.5, 1)))
graph <- list(LL = LL, LR = LR, RL = RL, RR = RR, OG = OG, GH = GH)
abbababa <- character(0)
for (k in seq(1, N)) {
	abbababa[length(abbababa) + 1] <- pattern(solve_tree(graph))
}
table <- table(abbababa)
tables[[length(tables) + 1]] <- table
# P12345 -> P2
LL <- list(lambda = lambda, inhabitants = character(0), samples = list(P1 = 0), switches = list(LR = c(1, 1)))
LR <- list(lambda = lambda, inhabitants = character(0), samples = list(P2 = 0), switches = list(RR = c(2, 1), GH = c(0.5, 0.1)))
RL <- list(lambda = lambda, inhabitants = character(0), samples = list(P3 = 0), switches = list(RR = c(1, 1)))
RR <- list(lambda = lambda, inhabitants = character(0), samples = list(P4 = 0), switches = list(OG = c(3, 1)))
OG <- list(lambda = lambda, inhabitants = character(0), samples = list(P5 = 0), switches = list())
GH <- list(lambda = lambda, inhabitants = character(0), samples = list(), switches = list(OG = c(3.5, 1)))
graph <- list(LL = LL, LR = LR, RL = RL, RR = RR, OG = OG, GH = GH)
abbababa <- character(0)
for (k in seq(1, N)) {
	abbababa[length(abbababa) + 1] <- pattern(solve_tree(graph))
}
table <- table(abbababa)
tables[[length(tables) + 1]] <- table
# P12345 -> P3
LL <- list(lambda = lambda, inhabitants = character(0), samples = list(P1 = 0), switches = list(LR = c(1, 1)))
LR <- list(lambda = lambda, inhabitants = character(0), samples = list(P2 = 0), switches = list(RR = c(2, 1)))
RL <- list(lambda = lambda, inhabitants = character(0), samples = list(P3 = 0), switches = list(RR = c(1, 1), GH = c(0.5, 0.1)))
RR <- list(lambda = lambda, inhabitants = character(0), samples = list(P4 = 0), switches = list(OG = c(3, 1)))
OG <- list(lambda = lambda, inhabitants = character(0), samples = list(P5 = 0), switches = list())
GH <- list(lambda = lambda, inhabitants = character(0), samples = list(), switches = list(OG = c(3.5, 1)))
graph <- list(LL = LL, LR = LR, RL = RL, RR = RR, OG = OG, GH = GH)
abbababa <- character(0)
for (k in seq(1, N)) {
	abbababa[length(abbababa) + 1] <- pattern(solve_tree(graph))
}
table <- table(abbababa)
tables[[length(tables) + 1]] <- table
# P12345 -> P4
LL <- list(lambda = lambda, inhabitants = character(0), samples = list(P1 = 0), switches = list(LR = c(1, 1)))
LR <- list(lambda = lambda, inhabitants = character(0), samples = list(P2 = 0), switches = list(RR = c(2, 1)))
RL <- list(lambda = lambda, inhabitants = character(0), samples = list(P3 = 0), switches = list(RR = c(1, 1)))
RR <- list(lambda = lambda, inhabitants = character(0), samples = list(P4 = 0), switches = list(OG = c(3, 1), GH = c(0.5, 0.1)))
OG <- list(lambda = lambda, inhabitants = character(0), samples = list(P5 = 0), switches = list())
GH <- list(lambda = lambda, inhabitants = character(0), samples = list(), switches = list(OG = c(3.5, 1)))
graph <- list(LL = LL, LR = LR, RL = RL, RR = RR, OG = OG, GH = GH)
abbababa <- character(0)
for (k in seq(1, N)) {
	abbababa[length(abbababa) + 1] <- pattern(solve_tree(graph))
}
table <- table(abbababa)
tables[[length(tables) + 1]] <- table
# P1234 -> P1
LL <- list(lambda = lambda, inhabitants = character(0), samples = list(P1 = 0), switches = list(LR = c(1, 1), GH = c(0.5, 0.1)))
LR <- list(lambda = lambda, inhabitants = character(0), samples = list(P2 = 0), switches = list(RR = c(2, 1)))
RL <- list(lambda = lambda, inhabitants = character(0), samples = list(P3 = 0), switches = list(RR = c(1, 1)))
RR <- list(lambda = lambda, inhabitants = character(0), samples = list(P4 = 0), switches = list(OG = c(3, 1)))
OG <- list(lambda = lambda, inhabitants = character(0), samples = list(P5 = 0), switches = list())
GH <- list(lambda = lambda, inhabitants = character(0), samples = list(), switches = list(RR = c(2.5, 1)))
graph <- list(LL = LL, LR = LR, RL = RL, RR = RR, OG = OG, GH = GH)
abbababa <- character(0)
for (k in seq(1, N)) {
	abbababa[length(abbababa) + 1] <- pattern(solve_tree(graph))
}
table <- table(abbababa)
tables[[length(tables) + 1]] <- table
# P1234 -> P2
LL <- list(lambda = lambda, inhabitants = character(0), samples = list(P1 = 0), switches = list(LR = c(1, 1)))
LR <- list(lambda = lambda, inhabitants = character(0), samples = list(P2 = 0), switches = list(RR = c(2, 1), GH = c(0.5, 0.1)))
RL <- list(lambda = lambda, inhabitants = character(0), samples = list(P3 = 0), switches = list(RR = c(1, 1)))
RR <- list(lambda = lambda, inhabitants = character(0), samples = list(P4 = 0), switches = list(OG = c(3, 1)))
OG <- list(lambda = lambda, inhabitants = character(0), samples = list(P5 = 0), switches = list())
GH <- list(lambda = lambda, inhabitants = character(0), samples = list(), switches = list(RR = c(2.5, 1)))
graph <- list(LL = LL, LR = LR, RL = RL, RR = RR, OG = OG, GH = GH)
abbababa <- character(0)
for (k in seq(1, N)) {
	abbababa[length(abbababa) + 1] <- pattern(solve_tree(graph))
}
table <- table(abbababa)
tables[[length(tables) + 1]] <- table
# P1234 -> P3
LL <- list(lambda = lambda, inhabitants = character(0), samples = list(P1 = 0), switches = list(LR = c(1, 1)))
LR <- list(lambda = lambda, inhabitants = character(0), samples = list(P2 = 0), switches = list(RR = c(2, 1)))
RL <- list(lambda = lambda, inhabitants = character(0), samples = list(P3 = 0), switches = list(RR = c(1, 1), GH = c(0.5, 0.1)))
RR <- list(lambda = lambda, inhabitants = character(0), samples = list(P4 = 0), switches = list(OG = c(3, 1)))
OG <- list(lambda = lambda, inhabitants = character(0), samples = list(P5 = 0), switches = list())
GH <- list(lambda = lambda, inhabitants = character(0), samples = list(), switches = list(RR = c(2.5, 1)))
graph <- list(LL = LL, LR = LR, RL = RL, RR = RR, OG = OG, GH = GH)
abbababa <- character(0)
for (k in seq(1, N)) {
	abbababa[length(abbababa) + 1] <- pattern(solve_tree(graph))
}
table <- table(abbababa)
tables[[length(tables) + 1]] <- table
# P1234 -> P4
LL <- list(lambda = lambda, inhabitants = character(0), samples = list(P1 = 0), switches = list(LR = c(1, 1)))
LR <- list(lambda = lambda, inhabitants = character(0), samples = list(P2 = 0), switches = list(RR = c(2, 1)))
RL <- list(lambda = lambda, inhabitants = character(0), samples = list(P3 = 0), switches = list(RR = c(1, 1)))
RR <- list(lambda = lambda, inhabitants = character(0), samples = list(P4 = 0), switches = list(OG = c(3, 1), GH = c(0.5, 0.1)))
OG <- list(lambda = lambda, inhabitants = character(0), samples = list(P5 = 0), switches = list())
GH <- list(lambda = lambda, inhabitants = character(0), samples = list(), switches = list(RR = c(2.5, 1)))
graph <- list(LL = LL, LR = LR, RL = RL, RR = RR, OG = OG, GH = GH)
abbababa <- character(0)
for (k in seq(1, N)) {
	abbababa[length(abbababa) + 1] <- pattern(solve_tree(graph))
}
table <- table(abbababa)
tables[[length(tables) + 1]] <- table

save(tables, file = "tables_S.RData")
```
